/*ALTER TABLE ASSETS ADD COLUMN BOOKKEEPINGTIME varchar(100) default '';
ALTER TABLE ASSETS ADD COLUMN VOUCHERNO varchar(100) default '';*/

-- ALTER TABLE DISPOSE_ASSET ADD COLUMN PARENT_CODE varchar(100) default '';
ALTER TABLE ZCQCY ADD COLUMN USER_TYPE varchar(10) default '';